layouts_dir:  _layouts
includes_dir: _includes
collections:
  projects:
    output: true
    permalink: /:collection/:name

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - education
